#曲率阈值、梯度阈值、诱导点下采样参数、诱导点数量
curvature_threshold: 0.1
gradient_threshold: 0.05
key_voxel_size: 0.1
inducing_points: 50
#sgp模型超参数设置
lengthscale: 0.7
alpha: 10
#地图分辨率、大小设置
resolution: 0.2
x_length: 5
y_length: 5
#坡度归一化参数
max_slope: 0.5
min_slope: 0.0
test_slope: 0
#曲率（不平坦度）归一化参数
max_flatness: 0.15
min_flatness: 0.0
test_flatness: 0
#梯度（阶梯度）归一化参数
max_height: 0.15
min_height: 0.0
test_height: 0
#不确定性归一化参数
max_uncertainty: 1.6
min_uncertainty: 0.64
test_uncertainty: 0
#可通行性初始值几何权重
w_slope: 1
w_flatness: 1
w_step_height: 5
